-- Create dimension tables
CREATE TABLE IF NOT EXISTS DIM_CUSTOMER (
    customer_id VARCHAR(10) PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    customer_region VARCHAR(50) NOT NULL,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DIM_PRODUCT (
    product_id VARCHAR(10) PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create fact table
CREATE TABLE IF NOT EXISTS FACT_ORDERS (
    order_id VARCHAR(10) PRIMARY KEY,
    order_timestamp TIMESTAMP_NTZ NOT NULL,
    customer_id VARCHAR(10) NOT NULL REFERENCES DIM_CUSTOMER(customer_id),
    product_id VARCHAR(10) NOT NULL REFERENCES DIM_PRODUCT(product_id),
    date_id DATE NOT NULL,
    quantity INT NOT NULL,
    total_amount DECIMAL(12,2) NOT NULL,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);